edns_client_subnet_private: 0
listen_addresses:
  - 127.0.0.1
  - 0::1
upstream_recursive_servers:
## Cloudflare
## Cloudflare 1.1.1.1 is a privacy centric resolver so it does not support EDNS Client Subnet.
## https://developers.cloudflare.com/1.1.1.1/nitty-gritty-details/#edns-client-subnet
#  - address_data: 1.1.1.1
#    tls_auth_name: "cloudflare-dns.com"
#  - address_data: 1.0.0.1
#    tls_auth_name: "cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1111
#    tls_auth_name: "cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1001
#    tls_auth_name: "cloudflare-dns.com"
## Cloudflare - Block Malware
#  - address_data: 1.1.1.2
#    tls_auth_name: "security.cloudflare-dns.com"
#  - address_data: 1.0.0.2
#    tls_auth_name: "security.cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1112
#    tls_auth_name: "security.cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1002
#    tls_auth_name: "security.cloudflare-dns.com"
## Cloudflare - Block Malware and Adult Content
#  - address_data: 1.1.1.3
#    tls_auth_name: "family.cloudflare-dns.com"
#  - address_data: 1.0.0.3
#    tls_auth_name: "family.cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1113
#    tls_auth_name: "family.cloudflare-dns.com"
#  - address_data: 2606:4700:4700::1003
#    tls_auth_name: "family.cloudflare-dns.com"
## Google
#  - address_data: 8.8.8.8
#    tls_auth_name: "dns.google"
#  - address_data: 8.8.4.4
#    tls_auth_name: "dns.google"
#  - address_data: 2001:4860:4860::8888
#    tls_auth_name: "dns.google"
#  - address_data: 2001:4860:4860::8844
#    tls_auth_name: "dns.google"
## Quad9 'recommended' service - Security blocklist, DNSSEC, No EDNS Client-Subnet sent
#  - address_data: 9.9.9.9
#    tls_auth_name: "dns.quad9.net"
#  - address_data: 149.112.112.112
#    tls_auth_name: "dns.quad9.net"
#  - address_data: 2620:fe::fe
#    tls_auth_name: "dns.quad9.net"
#  - address_data: 2620:fe::9
#    tls_auth_name: "dns.quad9.net"
## Quad9 'secured' service - Security blocklist, DNSSEC, No EDNS Client-Subnet sent
#  - address_data: 9.9.9.9
#    tls_auth_name: "dns9.quad9.net"
#  - address_data: 149.112.112.9
#    tls_auth_name: "dns9.quad9.net"
#  - address_data: 2620:fe::9
#    tls_auth_name: "dns9.quad9.net"
#  - address_data: 2620:fe::fe:9
#    tls_auth_name: "dns9.quad9.net"
## Quad9 'unsecured' service - No security blocklist, no DNSSEC, No EDNS Client-Subnet sent
#  - address_data: 9.9.9.10
#    tls_auth_name: "dns10.quad9.net"
#  - address_data: 149.112.112.10
#    tls_auth_name: "dns10.quad9.net"
#  - address_data: 2620:fe::10
#    tls_auth_name: "dns10.quad9.net"
#  - address_data: 2620:fe::fe:10
#    tls_auth_name: "dns10.quad9.net"
## Quad9 'secured w/ ECS support' service - Security blocklist, DNSSEC, EDNS Client-Subnet sent
#  - address_data: 9.9.9.11
#    tls_auth_name: "dns11.quad9.net"
#  - address_data: 149.112.112.11
#    tls_auth_name: "dns11.quad9.net"
#  - address_data: 2620:fe::11
#    tls_auth_name: "dns11.quad9.net"
#  - address_data: 2620:fe::fe:11
#    tls_auth_name: "dns11.quad9.net"
# NextDNS
  - address_data: 45.90.28.0
    tls_auth_name: "dns.nextdns.io"
  - address_data: 45.90.30.0
    tls_auth_name: "dns.nextdns.io"
  - address_data: 2a07:a8c0::0
    tls_auth_name: "dns.nextdns.io"
  - address_data: 2a07:a8c1::0
    tls_auth_name: "dns.nextdns.io"
