// Mozilla Preferences

defaultPref("browser.cache.disk.enable", false);
defaultPref("browser.cache.offline.enable", false);
defaultPref("browser.formfill.enable", false);
defaultPref("browser.region.network.url", "");
clearPref("browser.search.region");
defaultPref("datareporting.healthreport.uploadEnabled", false);
defaultPref("datareporting.policy.dataSubmissionEnabled", false);
defaultPref("extensions.getAddons.cache.enabled", false);
defaultPref("extensions.systemAddon.update.enabled", false);
defaultPref("mail.minimizeToTray", true);
defaultPref("mail.provider.enabled", false);
defaultPref("mail.rights.version", 1);
defaultPref("mail.sanitize_date_header", true);
defaultPref("mail.suppress_content_language", true);
defaultPref("mail.shell.checkDefaultClient", false);
defaultPref("mail.winsearch.firstRunDone", true);
defaultPref("mailnews.send_default_charset", "UTF-8");
defaultPref("mailnews.start_page.enabled", false);
pref("mailnews.start_page_override.mstone", "ignore");
defaultPref("mailnews.view_default_charset", "UTF-8");
defaultPref("media.peerconnection.ice.relay_only", true);
defaultPref("network.connectivity-service.enabled", false);
defaultPref("network.cookie.lifetimePolicy", 2);
defaultPref("network.http.referer.defaultPolicy", getPref("network.http.referer.defaultPolicy.pbmode"));
defaultPref("places.history.enabled", false);
defaultPref("privacy.firstparty.isolate", true);
defaultPref("privacy.resistFingerprinting", true);
defaultPref("security.OCSP.enabled", 2);
defaultPref("toolkit.telemetry.unified", false);
