// Mozilla Preferences

defaultPref("app.normandy.enabled", false);
defaultPref("browser.cache.disk.enable", false);
defaultPref("browser.cache.memory.capacity", getPref("browser.cache.disk.capacity"));
defaultPref("browser.cache.memory.max_entry_size", getPref("browser.cache.disk.max_entry_size"));
pref("browser.contentblocking.category", "strict");
defaultPref("browser.fixup.alternate.enabled", false);
defaultPref("browser.formfill.enable", false);
defaultPref("browser.region.network.url", "");
defaultPref("browser.safebrowsing.downloads.remote.enabled", false);
clearPref("browser.search.region");
defaultPref("browser.search.suggest.enabled", false);
defaultPref("browser.sessionstore.privacy_level", 2);
defaultPref("browser.sessionstore.resume_from_crash", false);
defaultPref("browser.shell.checkDefaultBrowser", false);
defaultPref("browser.startup.homepage", "https://www.wikipedia.org/");
pref("browser.startup.homepage_override.mstone", "ignore");
defaultPref("browser.tabs.crashReporting.sendReport", false);
defaultPref("browser.urlbar.dnsResolveSingleWordsAfterSearch", 0);
defaultPref("browser.urlbar.speculativeConnect.enabled", false);
defaultPref("datareporting.healthreport.uploadEnabled", false);
defaultPref("datareporting.policy.dataSubmissionEnabled", false);
defaultPref("extensions.getAddons.cache.enabled", false);
defaultPref("extensions.systemAddon.update.enabled", false);
defaultPref("media.gmp-manager.updateEnabled", false);
defaultPref("media.peerconnection.ice.relay_only", true);
defaultPref("network.captive-portal-service.enabled", false);
defaultPref("network.connectivity-service.enabled", false);
defaultPref("network.cookie.lifetimePolicy", 2);
defaultPref("places.history.enabled", false);
defaultPref("privacy.firstparty.isolate", true);
defaultPref("privacy.resistFingerprinting", true);
defaultPref("toolkit.telemetry.unified", false);
